{
    "frak08-b11.objy.com":
    {
        "config":"frak08.config"
        },
    "frak8.objy.com":
    {
    "config":"frak08.config"
    },
    "Henock-Abebes-MacBook-Pro.local":
    {
        "config":"habebe.macbook.config"
        },
    "dev-analysis-nosql-01.vega.ironport.com":
    {
        "config":"vega.ironport.01.config"
        }
    }
